#!/usr/bin/env bash

# Install script for per user log rotate configuration
#
# Files: logrotate.conf, logrotate.status, logrotate.service, logrotate.timer

mk_dir() {
	for d in "$@"; do
		mkdir -p "$d"
	done
}

#cp_files() {
#	for f in "$@"; do
#		echo "cp $f"
#	done
#}

systemd_dir="$HOME/.config/systemd/user"
config_dir="$HOME/.config/logrotate"
state_dir="$HOME/.local/logrotate"

mk_dir "$config_dir" "$state_dir" "$systemd_dir"
touch "$state_dir/logrotate.status"
cp logrotate.{service,timer} "$systemd_dir"
cp logrotate.conf "$config_dir"
cp logrotate.status "$state_dir"
chmod 600 "$state_dir/logrotate.status"

systemctl --user daemon-reload
systemctl --user enable logrotate.timer
